### ISSUE TITLE
Add ability to specify service requirements in hash-lookup

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/service-registry#8]
Rationale / use-case:
- If service A wants to contact service B,  but no instance of service B exists, it needs to allocate one. Part of the process of allocation is to identify a node that satisfies the service constraints of service B.
- Ideally need to consider both compute and network resource types:
  - For compute (e.g. CPU, RAM, etc.) requirements of service B, that can be done by identifying a node that has the available resources.
  - For network (e.g. latency, bandwidth, etc.) requirements, that must be identified _in relation to_ service A. In other words, the network path between service A and B must meet those requirements.

The hash-lookup service would thus return not only a docker hash associated with a service, but also its service requirements, such that the LCA manager can identify an appropriate target node / allocator.

**Comment by hivanco** [comment]
@t-lin Re: the discussion today (Jun 25), reading your original comment on this issue, it seems like I would still need to define a separate set of "allocation" requirements for compute resources. Using your example above, the CPU or RAM requirements for the node we allocate service B on could be different than the CPU or RAM requirements that service B's proxy uses when finding suitable peers to contact.

**Comment by t-lin** [comment]
I'm not quite sure what you mean. The way I'm thinking, when service B's proxy wants to find suitable peers to _contact_, it would focus more on those service's network requirements, since that's a relational metric (i.e. relative with respect to service B). We can hopefully assume that any instance of those services were allocated on nodes that meet their compute requirements. On the other hand, if service B's proxy wants to find peers to contact and can't find any, then it needs to find suitable nodes to _allocate_ on... and in this case it'd need to find nodes that meet the intended service's compute requirements (absolute) + network requirements (relative).

I suppose you could keep "allocation" separate to represent the compute requirements (e.g. CPU, RAM, etc.), which are absolute, and "perf" to mean network merics, which are relational/relative (i.e. RTT and bandwidth)?

Let me know if this is all still kinda fuzzy.
